### ISSUE TITLE
Cluster Mode

### ISSUE THREAD

**Issue by rbaid1221** [johndavedecano/node-rtmp-hls#7]
Hi on your read me, you have written that this has the ability to be run in a cluster.
How do you go ahead and set that up? Most of all how are you able to communicate between the different instances as all of this is transcoded and streamed in real time

**Comment by johndavedecano** [comment]
1. Create multiple instances
2. Use EFS to be used as mountpoint for all instances
3. Create en elastic load balancer  with sticky session

**Comment by rbaid1221** [comment]
Hi @johndavedecano I have already tried this, but this does not work. The sticky session does not work, because the Customer that is requesting the Live Streaming end point might be in a different location than the device that is actually uploading the RTMP Footage.

**Comment by rbaid1221** [comment]
In addition, using EFS doesn't help because EFS is a file storage system. In real time the video packets stay in memory, not written to a file.

**Comment by johndavedecano** [comment]
> In addition, using EFS doesn't help because EFS is a file storage system. In real-time, the video packets stay in memory, not written to a file.

You are correct but the use case for EFS is for the HLS files then you point you're, you mount the EFS on your EC2 then you serve them as static files and deliver using cloudfront

**Comment by rbaid1221** [comment]
@johndavedecano do you have a discord or anything of that sort, please?

**Comment by johndavedecano** [comment]
https://discord.gg/8vhwKyGK8X
